### ISSUE TITLE
Close pls

### ISSUE THREAD

**Issue by tope951** [kaicataldo/discord-transcript-generator#1]
How to use these packages the doc does not explain much

**Comment by kaicataldo** [comment]
Hi! Is there anything in particular that's confusing? I'd love to improve the README :)

**Comment by tope951** [comment]
I don't understand how to retrieve the messages in a channel for then create the transcript that she argues fingers put

Sorry for the mistakes I am French

**Comment by kaicataldo** [comment]
The tool is a CLI application. You can install it either locally in a project or globally. To generate the transcript, you run the following command in your terminal (replacing the values with the correct values for your use case):

```
generate-discord-transcript \
  --date=5/21/2020 \
  --output=./path/to/transcripts/2020-05-21.md \
  --id=735298510354839572 \
  --token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9 \
  --name="ESLint TSC Meeting"
```

A description of the arguments can be found [here](https://github.com/kaicataldo/discord-transcript-generator#arguments). You'll have to create a Discord Bot (on the Discord website) to get the token as well as enable it for the channel you'd like to generate a transcript from. [Here](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) is how to get the `id` of the channel you want to generate the transcript from.

Happy to answer any specific questions.

**Comment by tope951** [comment]
Close pls
