### ISSUE TITLE
Can I use this inside the bot?

### ISSUE THREAD

**Issue by TheDanniCraft** [kaicataldo/discord-transcript-generator#8]
I would like to create transcripts for my own Ticketsystem.
Do you have maybe some Code?

**Comment by kaicataldo** [comment]
Hi, do you mind clarifying what you're asking for? If you're asking for an example of how this can be used, [here](https://github.com/eslint/tsc-meetings/blob/master/.github/workflows/generate-transcript.yml) is an example of how a GitHub Action can utilize this package to generate transcripts in GitHub.

**Comment by TheDanniCraft** [comment]
I have codet my own ticketbot for Discord, that works fine. Now I would like to create a transcrip of the channel automaticly when a ticket gets closed. How can I automate this process?

**Comment by kaicataldo** [comment]
You should be able to use the examples in the readme and the repo I shared above to use the CLI to do this (I haven't officially created a Node API, though I wouldn't be against it).

**Comment by kaicataldo** [comment]
If you have any specific questions, please let me know.
